maxJobs: 100

outputDir: './' #set it to current dir (./) if running on a cluster, or to a gs storage bucket if running on GCP 

clusterMode: 'cluster' # or 'gcp' if running on gcp

useRemoteFiles: FALSE

refGenome: #full path to ref
bedFile: #full path to bed
bedFileGZ: #full path to gzipped bed
strelkaVCF: FALSE # full path to strelka2 VCF. Used if only harmonizing
haplotypecallerVCF: FALSE # full path to haplotypecaller VCF. Used if only harmonizing
deepvariantVCF: FALSE # full path to deepvariant VCF. Used if only harmonizing

runMode:
  streka2: TRUE
  haplotypeCaller: TRUE
  deepVariant: TRUE
  harmonize: TRUE  # will only be run if all callers are used

by_chrom: TRUE #if you like the workflow to be run by chromosome, FALSE if you like to to be run by sample
threads: 2

#glnexus parameters
glnexus_memGB: 16
glnexus_strelka2_config: #full path to config/strelka2_glnexus.yml
glnexus_gatk_config: 'gatk' # 'gatk' is optimized config or 'gatk_unfiltered'  if you have a small sample size (<1000) and you do not want any filtering
glnexus_dv_config: 'DeepVariantWES' #other options include DeepVariantWGS, DeepVariant_unfiltered


# DeepVariant parameters
model_type:  WES #or WGS if the samples are from WGS
dv_memGB: 16 #it is recommended that this memory to be set to roughly the same as the BAM file size

# Strelka2 parameters
exome_param:  '--exome'
strelka2_memGB: 16

